---
- name: Stop component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} stop'
  
- name: Remove the {{ component_name }} data prior to restore
  become: true
  file: 
    path: '{{ apigee_installation_home }}/data/{{ component_name }}'
    state: absent

- name: Restore component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} restore backup-{{ backup_time }}.tar.gz'

- name: Start component {{ component_name }}
  shell: '{{ apigee_service }} {{ component_name }} start'
